<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        // 🌍 EUROPA
        $europe = [
            ['code' => 'AL', 'iso3' => 'ALB', 'name' => 'Albânia', 'currency' => 'ALL', 'phone_code' => '+355'],
            ['code' => 'AD', 'iso3' => 'AND', 'name' => 'Andorra', 'currency' => 'EUR', 'phone_code' => '+376'],
            ['code' => 'AM', 'iso3' => 'ARM', 'name' => 'Arménia', 'currency' => 'AMD', 'phone_code' => '+374'],
            ['code' => 'AT', 'iso3' => 'AUT', 'name' => 'Áustria', 'currency' => 'EUR', 'phone_code' => '+43'],
            ['code' => 'AZ', 'iso3' => 'AZE', 'name' => 'Azerbaijão', 'currency' => 'AZN', 'phone_code' => '+994'],
            ['code' => 'BY', 'iso3' => 'BLR', 'name' => 'Bielorrússia', 'currency' => 'BYN', 'phone_code' => '+375'],
            ['code' => 'BE', 'iso3' => 'BEL', 'name' => 'Bélgica', 'currency' => 'EUR', 'phone_code' => '+32'],
            ['code' => 'BA', 'iso3' => 'BIH', 'name' => 'Bósnia e Herzegovina', 'currency' => 'BAM', 'phone_code' => '+387'],
            ['code' => 'BG', 'iso3' => 'BGR', 'name' => 'Bulgária', 'currency' => 'BGN', 'phone_code' => '+359'],
            ['code' => 'HR', 'iso3' => 'HRV', 'name' => 'Croácia', 'currency' => 'EUR', 'phone_code' => '+385'],
            ['code' => 'CY', 'iso3' => 'CYP', 'name' => 'Chipre', 'currency' => 'EUR', 'phone_code' => '+357'],
            ['code' => 'CZ', 'iso3' => 'CZE', 'name' => 'República Checa', 'currency' => 'CZK', 'phone_code' => '+420'],
            ['code' => 'DK', 'iso3' => 'DNK', 'name' => 'Dinamarca', 'currency' => 'DKK', 'phone_code' => '+45'],
            ['code' => 'EE', 'iso3' => 'EST', 'name' => 'Estónia', 'currency' => 'EUR', 'phone_code' => '+372'],
            ['code' => 'FI', 'iso3' => 'FIN', 'name' => 'Finlândia', 'currency' => 'EUR', 'phone_code' => '+358'],
            ['code' => 'FR', 'iso3' => 'FRA', 'name' => 'França', 'currency' => 'EUR', 'phone_code' => '+33'],
            ['code' => 'GE', 'iso3' => 'GEO', 'name' => 'Geórgia', 'currency' => 'GEL', 'phone_code' => '+995'],
            ['code' => 'DE', 'iso3' => 'DEU', 'name' => 'Alemanha', 'currency' => 'EUR', 'phone_code' => '+49'],
            ['code' => 'GR', 'iso3' => 'GRC', 'name' => 'Grécia', 'currency' => 'EUR', 'phone_code' => '+30'],
            ['code' => 'HU', 'iso3' => 'HUN', 'name' => 'Hungria', 'currency' => 'HUF', 'phone_code' => '+36'],
            ['code' => 'IS', 'iso3' => 'ISL', 'name' => 'Islândia', 'currency' => 'ISK', 'phone_code' => '+354'],
            ['code' => 'IE', 'iso3' => 'IRL', 'name' => 'Irlanda', 'currency' => 'EUR', 'phone_code' => '+353'],
            ['code' => 'IT', 'iso3' => 'ITA', 'name' => 'Itália', 'currency' => 'EUR', 'phone_code' => '+39'],
            ['code' => 'KZ', 'iso3' => 'KAZ', 'name' => 'Cazaquistão', 'currency' => 'KZT', 'phone_code' => '+7'],
            ['code' => 'XK', 'iso3' => 'XKX', 'name' => 'Kosovo', 'currency' => 'EUR', 'phone_code' => '+383'],
            ['code' => 'LV', 'iso3' => 'LVA', 'name' => 'Letónia', 'currency' => 'EUR', 'phone_code' => '+371'],
            ['code' => 'LI', 'iso3' => 'LIE', 'name' => 'Liechtenstein', 'currency' => 'CHF', 'phone_code' => '+423'],
            ['code' => 'LT', 'iso3' => 'LTU', 'name' => 'Lituânia', 'currency' => 'EUR', 'phone_code' => '+370'],
            ['code' => 'LU', 'iso3' => 'LUX', 'name' => 'Luxemburgo', 'currency' => 'EUR', 'phone_code' => '+352'],
            ['code' => 'MT', 'iso3' => 'MLT', 'name' => 'Malta', 'currency' => 'EUR', 'phone_code' => '+356'],
            ['code' => 'MD', 'iso3' => 'MDA', 'name' => 'Moldávia', 'currency' => 'MDL', 'phone_code' => '+373'],
            ['code' => 'MC', 'iso3' => 'MCO', 'name' => 'Mónaco', 'currency' => 'EUR', 'phone_code' => '+377'],
            ['code' => 'ME', 'iso3' => 'MNE', 'name' => 'Montenegro', 'currency' => 'EUR', 'phone_code' => '+382'],
            ['code' => 'NL', 'iso3' => 'NLD', 'name' => 'Países Baixos', 'currency' => 'EUR', 'phone_code' => '+31'],
            ['code' => 'MK', 'iso3' => 'MKD', 'name' => 'Macedónia do Norte', 'currency' => 'MKD', 'phone_code' => '+389'],
            ['code' => 'NO', 'iso3' => 'NOR', 'name' => 'Noruega', 'currency' => 'NOK', 'phone_code' => '+47'],
            ['code' => 'PL', 'iso3' => 'POL', 'name' => 'Polónia', 'currency' => 'PLN', 'phone_code' => '+48'],
            ['code' => 'PT', 'iso3' => 'PRT', 'name' => 'Portugal', 'currency' => 'EUR', 'phone_code' => '+351'],
            ['code' => 'RO', 'iso3' => 'ROU', 'name' => 'Roménia', 'currency' => 'RON', 'phone_code' => '+40'],
            ['code' => 'RU', 'iso3' => 'RUS', 'name' => 'Rússia', 'currency' => 'RUB', 'phone_code' => '+7'],
            ['code' => 'SM', 'iso3' => 'SMR', 'name' => 'San Marino', 'currency' => 'EUR', 'phone_code' => '+378'],
            ['code' => 'RS', 'iso3' => 'SRB', 'name' => 'Sérvia', 'currency' => 'RSD', 'phone_code' => '+381'],
            ['code' => 'SK', 'iso3' => 'SVK', 'name' => 'Eslováquia', 'currency' => 'EUR', 'phone_code' => '+421'],
            ['code' => 'SI', 'iso3' => 'SVN', 'name' => 'Eslovénia', 'currency' => 'EUR', 'phone_code' => '+386'],
            ['code' => 'ES', 'iso3' => 'ESP', 'name' => 'Espanha', 'currency' => 'EUR', 'phone_code' => '+34'],
            ['code' => 'SE', 'iso3' => 'SWE', 'name' => 'Suécia', 'currency' => 'SEK', 'phone_code' => '+46'],
            ['code' => 'CH', 'iso3' => 'CHE', 'name' => 'Suíça', 'currency' => 'CHF', 'phone_code' => '+41'],
            ['code' => 'TR', 'iso3' => 'TUR', 'name' => 'Turquia', 'currency' => 'TRY', 'phone_code' => '+90'],
            ['code' => 'UA', 'iso3' => 'UKR', 'name' => 'Ucrânia', 'currency' => 'UAH', 'phone_code' => '+380'],
            ['code' => 'GB', 'iso3' => 'GBR', 'name' => 'Reino Unido', 'currency' => 'GBP', 'phone_code' => '+44'],
            ['code' => 'VA', 'iso3' => 'VAT', 'name' => 'Vaticano', 'currency' => 'EUR', 'phone_code' => '+379'],
        ];
        // 🌍 ÁFRICA
        $africa = [
            ['code' => 'DZ', 'iso3' => 'DZA', 'name' => 'Argélia', 'currency' => 'DZD', 'phone_code' => '+213'],
            ['code' => 'AO', 'iso3' => 'AGO', 'name' => 'Angola', 'currency' => 'AOA', 'phone_code' => '+244'],
            ['code' => 'BJ', 'iso3' => 'BEN', 'name' => 'Benim', 'currency' => 'XOF', 'phone_code' => '+229'],
            ['code' => 'BW', 'iso3' => 'BWA', 'name' => 'Botswana', 'currency' => 'BWP', 'phone_code' => '+267'],
            ['code' => 'BF', 'iso3' => 'BFA', 'name' => 'Burkina Faso', 'currency' => 'XOF', 'phone_code' => '+226'],
            ['code' => 'BI', 'iso3' => 'BDI', 'name' => 'Burundi', 'currency' => 'BIF', 'phone_code' => '+257'],
            ['code' => 'CM', 'iso3' => 'CMR', 'name' => 'Camarões', 'currency' => 'XAF', 'phone_code' => '+237'],
            ['code' => 'CV', 'iso3' => 'CPV', 'name' => 'Cabo Verde', 'currency' => 'CVE', 'phone_code' => '+238'],
            ['code' => 'CF', 'iso3' => 'CAF', 'name' => 'República Centro-Africana', 'currency' => 'XAF', 'phone_code' => '+236'],
            ['code' => 'TD', 'iso3' => 'TCD', 'name' => 'Chade', 'currency' => 'XAF', 'phone_code' => '+235'],
            ['code' => 'KM', 'iso3' => 'COM', 'name' => 'Comores', 'currency' => 'KMF', 'phone_code' => '+269'],
            ['code' => 'CG', 'iso3' => 'COG', 'name' => 'Congo', 'currency' => 'XAF', 'phone_code' => '+242'],
            ['code' => 'CD', 'iso3' => 'COD', 'name' => 'Congo (RDC)', 'currency' => 'CDF', 'phone_code' => '+243'],
            ['code' => 'CI', 'iso3' => 'CIV', 'name' => 'Costa do Marfim', 'currency' => 'XOF', 'phone_code' => '+225'],
            ['code' => 'DJ', 'iso3' => 'DJI', 'name' => 'Djibouti', 'currency' => 'DJF', 'phone_code' => '+253'],
            ['code' => 'EG', 'iso3' => 'EGY', 'name' => 'Egito', 'currency' => 'EGP', 'phone_code' => '+20'],
            ['code' => 'ER', 'iso3' => 'ERI', 'name' => 'Eritreia', 'currency' => 'ERN', 'phone_code' => '+291'],
            ['code' => 'SZ', 'iso3' => 'SWZ', 'name' => 'Eswatini', 'currency' => 'SZL', 'phone_code' => '+268'],
            ['code' => 'ET', 'iso3' => 'ETH', 'name' => 'Etiópia', 'currency' => 'ETB', 'phone_code' => '+251'],
            ['code' => 'GA', 'iso3' => 'GAB', 'name' => 'Gabão', 'currency' => 'XAF', 'phone_code' => '+241'],
            ['code' => 'GM', 'iso3' => 'GMB', 'name' => 'Gâmbia', 'currency' => 'GMD', 'phone_code' => '+220'],
            ['code' => 'GH', 'iso3' => 'GHA', 'name' => 'Gana', 'currency' => 'GHS', 'phone_code' => '+233'],
            ['code' => 'GN', 'iso3' => 'GIN', 'name' => 'Guiné', 'currency' => 'GNF', 'phone_code' => '+224'],
            ['code' => 'GW', 'iso3' => 'GNB', 'name' => 'Guiné-Bissau', 'currency' => 'XOF', 'phone_code' => '+245'],
            ['code' => 'KE', 'iso3' => 'KEN', 'name' => 'Quénia', 'currency' => 'KES', 'phone_code' => '+254'],
            ['code' => 'LS', 'iso3' => 'LSO', 'name' => 'Lesoto', 'currency' => 'LSL', 'phone_code' => '+266'],
            ['code' => 'LR', 'iso3' => 'LBR', 'name' => 'Libéria', 'currency' => 'LRD', 'phone_code' => '+231'],
            ['code' => 'LY', 'iso3' => 'LBY', 'name' => 'Líbia', 'currency' => 'LYD', 'phone_code' => '+218'],
            ['code' => 'MG', 'iso3' => 'MDG', 'name' => 'Madagáscar', 'currency' => 'MGA', 'phone_code' => '+261'],
            ['code' => 'MW', 'iso3' => 'MWI', 'name' => 'Malawi', 'currency' => 'MWK', 'phone_code' => '+265'],
            ['code' => 'ML', 'iso3' => 'MLI', 'name' => 'Mali', 'currency' => 'XOF', 'phone_code' => '+223'],
            ['code' => 'MR', 'iso3' => 'MRT', 'name' => 'Mauritânia', 'currency' => 'MRU', 'phone_code' => '+222'],
            ['code' => 'MU', 'iso3' => 'MUS', 'name' => 'Maurícia', 'currency' => 'MUR', 'phone_code' => '+230'],
            ['code' => 'MA', 'iso3' => 'MAR', 'name' => 'Marrocos', 'currency' => 'MAD', 'phone_code' => '+212'],
            ['code' => 'MZ', 'iso3' => 'MOZ', 'name' => 'Moçambique', 'currency' => 'MZN', 'phone_code' => '+258'],
            ['code' => 'NA', 'iso3' => 'NAM', 'name' => 'Namíbia', 'currency' => 'NAD', 'phone_code' => '+264'],
            ['code' => 'NE', 'iso3' => 'NER', 'name' => 'Níger', 'currency' => 'XOF', 'phone_code' => '+227'],
            ['code' => 'NG', 'iso3' => 'NGA', 'name' => 'Nigéria', 'currency' => 'NGN', 'phone_code' => '+234'],
            ['code' => 'RW', 'iso3' => 'RWA', 'name' => 'Ruanda', 'currency' => 'RWF', 'phone_code' => '+250'],
            ['code' => 'SN', 'iso3' => 'SEN', 'name' => 'Senegal', 'currency' => 'XOF', 'phone_code' => '+221'],
            ['code' => 'SC', 'iso3' => 'SYC', 'name' => 'Seicheles', 'currency' => 'SCR', 'phone_code' => '+248'],
            ['code' => 'SL', 'iso3' => 'SLE', 'name' => 'Serra Leoa', 'currency' => 'SLL', 'phone_code' => '+232'],
            ['code' => 'SO', 'iso3' => 'SOM', 'name' => 'Somália', 'currency' => 'SOS', 'phone_code' => '+252'],
            ['code' => 'ZA', 'iso3' => 'ZAF', 'name' => 'África do Sul', 'currency' => 'ZAR', 'phone_code' => '+27'],
            ['code' => 'SS', 'iso3' => 'SSD', 'name' => 'Sudão do Sul', 'currency' => 'SSP', 'phone_code' => '+211'],
            ['code' => 'SD', 'iso3' => 'SDN', 'name' => 'Sudão', 'currency' => 'SDG', 'phone_code' => '+249'],
            ['code' => 'TZ', 'iso3' => 'TZA', 'name' => 'Tanzânia', 'currency' => 'TZS', 'phone_code' => '+255'],
            ['code' => 'TG', 'iso3' => 'TGO', 'name' => 'Togo', 'currency' => 'XOF', 'phone_code' => '+228'],
            ['code' => 'TN', 'iso3' => 'TUN', 'name' => 'Tunísia', 'currency' => 'TND', 'phone_code' => '+216'],
            ['code' => 'UG', 'iso3' => 'UGA', 'name' => 'Uganda', 'currency' => 'UGX', 'phone_code' => '+256'],
            ['code' => 'ZM', 'iso3' => 'ZMB', 'name' => 'Zâmbia', 'currency' => 'ZMW', 'phone_code' => '+260'],
            ['code' => 'ZW', 'iso3' => 'ZWE', 'name' => 'Zimbábue', 'currency' => 'ZWL', 'phone_code' => '+263'],
        ];
        // 🌎 AMÉRICAS
        $americas = [
            ['code' => 'US', 'iso3' => 'USA', 'name' => 'Estados Unidos', 'currency' => 'USD', 'phone_code' => '+1'],
            ['code' => 'CA', 'iso3' => 'CAN', 'name' => 'Canadá', 'currency' => 'CAD', 'phone_code' => '+1'],
            ['code' => 'BR', 'iso3' => 'BRA', 'name' => 'Brasil', 'currency' => 'BRL', 'phone_code' => '+55'],
            ['code' => 'AR', 'iso3' => 'ARG', 'name' => 'Argentina', 'currency' => 'ARS', 'phone_code' => '+54'],
            ['code' => 'MX', 'iso3' => 'MEX', 'name' => 'México', 'currency' => 'MXN', 'phone_code' => '+52'],
            ['code' => 'CL', 'iso3' => 'CHL', 'name' => 'Chile', 'currency' => 'CLP', 'phone_code' => '+56'],
            ['code' => 'CO', 'iso3' => 'COL', 'name' => 'Colômbia', 'currency' => 'COP', 'phone_code' => '+57'],
            ['code' => 'PE', 'iso3' => 'PER', 'name' => 'Peru', 'currency' => 'PEN', 'phone_code' => '+51'],
            ['code' => 'UY', 'iso3' => 'URY', 'name' => 'Uruguai', 'currency' => 'UYU', 'phone_code' => '+598'],
            ['code' => 'PY', 'iso3' => 'PRY', 'name' => 'Paraguai', 'currency' => 'PYG', 'phone_code' => '+595'],
            ['code' => 'BO', 'iso3' => 'BOL', 'name' => 'Bolívia', 'currency' => 'BOB', 'phone_code' => '+591'],
            ['code' => 'VE', 'iso3' => 'VEN', 'name' => 'Venezuela', 'currency' => 'VES', 'phone_code' => '+58'],
            ['code' => 'EC', 'iso3' => 'ECU', 'name' => 'Equador', 'currency' => 'USD', 'phone_code' => '+593'],
            ['code' => 'CU', 'iso3' => 'CUB', 'name' => 'Cuba', 'currency' => 'CUP', 'phone_code' => '+53'],
            ['code' => 'CR', 'iso3' => 'CRI', 'name' => 'Costa Rica', 'currency' => 'CRC', 'phone_code' => '+506'],
            ['code' => 'DO', 'iso3' => 'DOM', 'name' => 'República Dominicana', 'currency' => 'DOP', 'phone_code' => '+1'],
            ['code' => 'GT', 'iso3' => 'GTM', 'name' => 'Guatemala', 'currency' => 'GTQ', 'phone_code' => '+502'],
            ['code' => 'HN', 'iso3' => 'HND', 'name' => 'Honduras', 'currency' => 'HNL', 'phone_code' => '+504'],
            ['code' => 'NI', 'iso3' => 'NIC', 'name' => 'Nicarágua', 'currency' => 'NIO', 'phone_code' => '+505'],
            ['code' => 'PA', 'iso3' => 'PAN', 'name' => 'Panamá', 'currency' => 'PAB', 'phone_code' => '+507'],
        ];

        // 🌏 ÁSIA
        $asia = [
            ['code' => 'CN', 'iso3' => 'CHN', 'name' => 'China', 'currency' => 'CNY', 'phone_code' => '+86'],
            ['code' => 'JP', 'iso3' => 'JPN', 'name' => 'Japão', 'currency' => 'JPY', 'phone_code' => '+81'],
            ['code' => 'IN', 'iso3' => 'IND', 'name' => 'Índia', 'currency' => 'INR', 'phone_code' => '+91'],
            ['code' => 'KR', 'iso3' => 'KOR', 'name' => 'Coreia do Sul', 'currency' => 'KRW', 'phone_code' => '+82'],
            ['code' => 'ID', 'iso3' => 'IDN', 'name' => 'Indonésia', 'currency' => 'IDR', 'phone_code' => '+62'],
            ['code' => 'TH', 'iso3' => 'THA', 'name' => 'Tailândia', 'currency' => 'THB', 'phone_code' => '+66'],
            ['code' => 'VN', 'iso3' => 'VNM', 'name' => 'Vietname', 'currency' => 'VND', 'phone_code' => '+84'],
            ['code' => 'MY', 'iso3' => 'MYS', 'name' => 'Malásia', 'currency' => 'MYR', 'phone_code' => '+60'],
            ['code' => 'SG', 'iso3' => 'SGP', 'name' => 'Singapura', 'currency' => 'SGD', 'phone_code' => '+65'],
            ['code' => 'PH', 'iso3' => 'PHL', 'name' => 'Filipinas', 'currency' => 'PHP', 'phone_code' => '+63'],
            ['code' => 'AE', 'iso3' => 'ARE', 'name' => 'Emirados Árabes Unidos', 'currency' => 'AED', 'phone_code' => '+971'],
            ['code' => 'SA', 'iso3' => 'SAU', 'name' => 'Arábia Saudita', 'currency' => 'SAR', 'phone_code' => '+966'],
            ['code' => 'QA', 'iso3' => 'QAT', 'name' => 'Catar', 'currency' => 'QAR', 'phone_code' => '+974'],
            ['code' => 'KW', 'iso3' => 'KWT', 'name' => 'Kuwait', 'currency' => 'KWD', 'phone_code' => '+965'],
            ['code' => 'IR', 'iso3' => 'IRN', 'name' => 'Irão', 'currency' => 'IRR', 'phone_code' => '+98'],
            ['code' => 'IL', 'iso3' => 'ISR', 'name' => 'Israel', 'currency' => 'ILS', 'phone_code' => '+972'],
            ['code' => 'PK', 'iso3' => 'PAK', 'name' => 'Paquistão', 'currency' => 'PKR', 'phone_code' => '+92'],
            ['code' => 'BD', 'iso3' => 'BGD', 'name' => 'Bangladesh', 'currency' => 'BDT', 'phone_code' => '+880'],
            ['code' => 'LK', 'iso3' => 'LKA', 'name' => 'Sri Lanka', 'currency' => 'LKR', 'phone_code' => '+94'],
            ['code' => 'NP', 'iso3' => 'NPL', 'name' => 'Nepal', 'currency' => 'NPR', 'phone_code' => '+977'],
        ];

        // 🌏 OCEANIA
        $oceania = [
            ['code' => 'AU', 'iso3' => 'AUS', 'name' => 'Austrália', 'currency' => 'AUD', 'phone_code' => '+61'],
            ['code' => 'NZ', 'iso3' => 'NZL', 'name' => 'Nova Zelândia', 'currency' => 'NZD', 'phone_code' => '+64'],
            ['code' => 'FJ', 'iso3' => 'FJI', 'name' => 'Fiji', 'currency' => 'FJD', 'phone_code' => '+679'],
            ['code' => 'PG', 'iso3' => 'PNG', 'name' => 'Papua-Nova Guiné', 'currency' => 'PGK', 'phone_code' => '+675'],
            ['code' => 'SB', 'iso3' => 'SLB', 'name' => 'Ilhas Salomão', 'currency' => 'SBD', 'phone_code' => '+677'],
            ['code' => 'TO', 'iso3' => 'TON', 'name' => 'Tonga', 'currency' => 'TOP', 'phone_code' => '+676'],
            ['code' => 'WS', 'iso3' => 'WSM', 'name' => 'Samoa', 'currency' => 'WST', 'phone_code' => '+685'],
            ['code' => 'VU', 'iso3' => 'VUT', 'name' => 'Vanuatu', 'currency' => 'VUV', 'phone_code' => '+678'],
            ['code' => 'FM', 'iso3' => 'FSM', 'name' => 'Micronésia', 'currency' => 'USD', 'phone_code' => '+691'],
        ];

        // Junta tudo
        $countries = array_merge($europe, $africa, $americas, $asia, $oceania);

        // Inserção
        $this->db->table('conf_countries')->insertBatch($countries);
    }
}
